export const GET_TOPICS = 'GET TOPICS';
export const GET_RESOURCE = 'GET RESOURCE';
export const UPDATE_TOPIC = 'UPDATE TOPIC';
export const ADD_RESOURCE = 'ADD RESOURCE';
export const UPVOTE = 'UPVOTE';
export const DOWNVOTE = 'DOWNVOTE';
export const LOGIN = 'LOGIN';
export const ADD_FAV = 'ADD FAV';
export const DELETE_FAV = 'DELETE FAV';
export const GET_USER_INFO = 'GET USER INFO'